site_name: Nan-kuei

theme:
  name: material
#  name: readthedocs

nav:
  - links: links.md
  - mkdocs: using_mkdocs.md
  - jupyterbook: using_jupyterbook.md
  - ASL denoising: asl_denoising.md
  - GUI for pulseq programming: pulseq.md
#  - page: using_mkdocs.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
